name: leaf_smart
description: "LeafSmart - Nurture Nature with Intelligence"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_svg: ^2.0.10+1
  image: 4.2.0
  animated_text_kit: ^4.2.1
  image_picker: ^1.1.2
  http: ^1.2.2
  geolocator: ^13.0.1
  provider: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.1.10
  flutter_blue_plus: ^1.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/
      - assets/user_avatar.png
      - assets/bot_avatar.png